Exercise 1 : Array Creation and Manipulation
===
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np


In [3]:
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


_____________________

Exercise 2 : Type Conversion and Array Operations
=====
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:

array([3, 2, 0, 1, 2])

In [11]:
float_list = [3.14, 2.17, 0, 1, 2]
arr = np.array(float_list).astype(int)
print(repr(arr))

array([3, 2, 0, 1, 2])


_________________________

Exercise 3 : Working with Multi-Dimensional Arrays
====
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
matrix = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

print(repr(matrix))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


________________________

Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
===
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [9]:
random_array = np.random.rand(4,5)

clean_array = np.round(random_array, 2)

print(repr(clean_array))

array([[0.44, 0.22, 0.54, 0.11, 0.28],
       [0.87, 0.52, 0.81, 0.22, 0.11],
       [0.27, 0.78, 0.1 , 0.68, 0.17],
       [0.87, 0.56, 0.49, 0.6 , 0.31]])


____________________

Exercise 5 : Indexing Arrays
===
Instructions:


Select the second row from a given 2D NumPy array.

In [12]:
array = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])

second_row = array[1]

print(repr(second_row))

array([20, 21, 22, 23, 24])


__________________

Exercise 6 : Reversing elements
===
Instructions


Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [13]:
array = ([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

print(array[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


______________

Exercise 7 : Identity Matrix
====
Instructions

Create a 4x4 identity matrix using NumPy.

In [14]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


_________________

Exercise 8 : Simple Aggregate Funcs
===
Instructions

Find the sum and average of a given 1D array.

In [15]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

total_sum = np.sum(array)

average = np.mean(array)

print(f"Sum: {total_sum}, Average: {average}")

Sum: 45, Average: 4.5


________________

Exercise 9 : Create Array and Change its Structure
===
Instructions:

Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [17]:
arr = np.arange(1,21).reshape(4, 5)

print(repr(arr))


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


__________

Exercise 10 : Conditional Selection of Values
===
Instructions

Extract all odd numbers from a given NumPy array.

In [18]:
array = np.arange(10)

odd_numbers = array[array % 2 != 0]

print(repr(odd_numbers))

array([1, 3, 5, 7, 9])
